/**
 * Swymble MCP server.
 *
 * Exposes the site's public content — labs, client projects, writing, and the studio overview —
 * as Model Context Protocol tools, so an MCP client can answer "what is MyDompet?" or "which
 * Swymble labs are live?" without driving a browser or scraping a page.
 *
 * These are the same five tools src/hooks/useWebMcp.ts registers for in-page browser agents. The
 * duplication is deliberate: WebMCP reaches an agent already looking at the site, this reaches
 * every other client, and neither can serve the other's audience.
 *
 * ---------------------------------------------------------------------------
 * DESIGN NOTES
 * ---------------------------------------------------------------------------
 * - Read-only. There is no tool that submits the contact form. An agent that can send mail on a
 *   visitor's behalf, unprompted, is a spam vector pointed at a personal inbox — and the form is
 *   one click away for the human who actually wants it.
 * - Stateless. No sessions, no `Mcp-Session-Id`, no server-initiated streams. Every request is
 *   self-contained, which is what lets this run on a Worker with no storage binding at all.
 * - Unauthenticated, because every byte it serves is already public on swymble.com. That is why
 *   there is no OAuth metadata to go with it: there is no protected resource here to protect.
 * - Content comes from https://swymble.com/site-data.json, regenerated by every site build
 *   (scripts/generate-site-data.mjs), so the server cannot drift from the site. Baking the data
 *   into this file would mean serving stale labs until someone remembered to redeploy.
 *
 * ---------------------------------------------------------------------------
 * DEPLOYMENT
 * ---------------------------------------------------------------------------
 *   npx wrangler deploy --config cloudflare/mcp-worker.wrangler.toml
 *
 * Then set the MCP_SERVER_URL repository variable to the deployed URL, so the next site build
 * publishes /.well-known/mcp/server-card.json pointing at it. The card is generated only when
 * that variable is set — a card advertising an endpoint that was never deployed is worse than no
 * card, because an agent pays a connection timeout to discover it.
 *
 * Endpoint: POST https://<host>/mcp
 */

const SERVER_NAME = 'swymble';
const SERVER_VERSION = '1.0.0';

/** The MCP revisions this server can speak. Unknown versions get the newest one back. */
const SUPPORTED_PROTOCOL_VERSIONS = ['2025-06-18', '2025-03-26', '2024-11-05'];
const DEFAULT_PROTOCOL_VERSION = SUPPORTED_PROTOCOL_VERSIONS[0];

const SITE_DATA_URL = 'https://swymble.com/site-data.json';
const SITE_DATA_TTL_SECONDS = 900;
const SUPPORTED_SCHEMA_VERSION = 1;

/** A JSON-RPC request body has no business being large; this one's largest legitimate call is tiny. */
const MAX_BODY_BYTES = 64 * 1024;
/** Free-text tool arguments are clamped before use, and again before appearing in any error. */
const MAX_QUERY_LENGTH = 200;

// ---------------------------------------------------------------------------
// JSON-RPC plumbing
// ---------------------------------------------------------------------------

const JSON_RPC_PARSE_ERROR = -32700;
const JSON_RPC_INVALID_REQUEST = -32600;
const JSON_RPC_METHOD_NOT_FOUND = -32601;
const JSON_RPC_INVALID_PARAMS = -32602;
const JSON_RPC_INTERNAL_ERROR = -32603;

/**
 * `*` is correct here and safe *because* the server is unauthenticated and read-only: there is
 * no cookie, no credential and no per-caller state for a hostile page to reach. Credentials are
 * never allowed — `Access-Control-Allow-Credentials` is deliberately absent, which is what stops
 * `*` from ever being combined with an authenticated request.
 */
const corsHeaders = () => ({
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Accept, MCP-Protocol-Version',
  'Access-Control-Max-Age': '86400',
});

const jsonResponse = (payload, status = 200) =>
  new Response(JSON.stringify(payload), {
    status,
    headers: { 'Content-Type': 'application/json; charset=utf-8', ...corsHeaders() },
  });

/** JSON-RPC ids may be a string, a number or null — anything else is not a valid id. */
const normaliseId = (id) => (typeof id === 'string' || typeof id === 'number' ? id : null);

const rpcResult = (id, result) => ({ jsonrpc: '2.0', id: normaliseId(id), result });

const rpcError = (id, code, message) => ({
  jsonrpc: '2.0',
  id: normaliseId(id),
  error: { code, message },
});

// ---------------------------------------------------------------------------
// Site data
// ---------------------------------------------------------------------------

/**
 * Fetched through the Cloudflare cache rather than a module-scope variable. Worker isolates are
 * recycled unpredictably, so an in-memory cache would be a cache with an unknowable hit rate;
 * `cf.cacheTtl` gives a bounded, shared one and keeps this from hammering the origin under load.
 *
 * The URL is a module constant. Nothing a caller sends can influence it, which is what keeps this
 * from being an SSRF gadget — the Worker will only ever fetch this one document.
 */
const loadSiteData = async () => {
  const response = await fetch(SITE_DATA_URL, {
    cf: { cacheTtl: SITE_DATA_TTL_SECONDS, cacheEverything: true },
    headers: { Accept: 'application/json' },
  });

  if (!response.ok) {
    throw new Error(`site-data.json unavailable (HTTP ${response.status})`);
  }

  const data = await response.json();

  // Refuse data this build of the Worker does not understand, rather than returning tool results
  // silently missing half their fields.
  if (data?.schemaVersion !== SUPPORTED_SCHEMA_VERSION) {
    throw new Error(`site-data.json schema version ${data?.schemaVersion} is not supported`);
  }

  return data;
};

// ---------------------------------------------------------------------------
// Tools
// ---------------------------------------------------------------------------

const TOOL_DEFINITIONS = [
  {
    name: 'get_swymble_overview',
    description:
      'Get a factual summary of Swymble: what it is, the services it offers, where it is based, how to make contact, and the full list of frequently asked questions. Use this to answer "what is Swymble?".',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
  },
  {
    name: 'list_swymble_labs',
    description:
      'List the products built by Swymble Labs, optionally filtered by status. Returns each product with its summary, status, page on swymble.com, and the URL of the Markdown version.',
    inputSchema: {
      type: 'object',
      properties: {
        status: {
          type: 'string',
          enum: ['Live', 'In Development', 'Private Beta'],
          description: 'Only return labs with this status. Omit to return all of them.',
        },
      },
      additionalProperties: false,
    },
  },
  {
    name: 'get_swymble_lab',
    description:
      'Get the full description of one Swymble Labs product by id (for example "mydompet", "territory", "cortex"): overview, features, specifications, highlights and FAQ.',
    inputSchema: {
      type: 'object',
      properties: { id: { type: 'string', description: 'The lab id, as returned by list_swymble_labs.' } },
      required: ['id'],
      additionalProperties: false,
    },
  },
  {
    name: 'list_swymble_projects',
    description: 'List the client projects Swymble has shipped, with the client, what was built, and the live site.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
  },
  {
    name: 'search_swymble_writing',
    description:
      'Search Swymble blog posts by keyword across their titles and summaries. Returns matching posts with their URLs. Omit the query to list every post.',
    inputSchema: {
      type: 'object',
      properties: { query: { type: 'string', description: 'Keyword or phrase to match.' } },
      additionalProperties: false,
    },
  },
];

const TOOL_NAMES = new Set(TOOL_DEFINITIONS.map((tool) => tool.name));

/** Trims and length-caps a free-text argument before it is used or echoed anywhere. */
const readStringArg = (args, key) => {
  const value = args?.[key];
  return typeof value === 'string' ? value.trim().slice(0, MAX_QUERY_LENGTH) : '';
};

const toolResult = (payload) => ({
  content: [{ type: 'text', text: JSON.stringify(payload, null, 2) }],
});

const toolError = (message) => ({
  content: [{ type: 'text', text: message }],
  isError: true,
});

const runTool = async (name, args) => {
  const data = await loadSiteData();

  switch (name) {
    case 'get_swymble_overview':
      return toolResult({ ...data.site, services: data.services, faq: data.faq });

    case 'list_swymble_labs': {
      const status = readStringArg(args, 'status');
      const labs = data.labs.filter((lab) => !status || lab.status === status);
      return toolResult({
        count: labs.length,
        labs: labs.map(({ id, name: labName, category, status: labStatus, summary, page, updatedAt }) => ({
          id,
          name: labName,
          category,
          status: labStatus,
          summary,
          page,
          updatedAt,
        })),
      });
    }

    case 'get_swymble_lab': {
      const id = readStringArg(args, 'id').toLowerCase();

      if (!id) {
        return toolError('The "id" argument is required. Call list_swymble_labs to see the available ids.');
      }

      // Object.hasOwn-style lookup via find on an array — never a bare property access on an
      // object keyed by caller input, which is how prototype keys ("__proto__") sneak in.
      const lab = data.labs.find((entry) => entry.id === id);

      if (!lab) {
        return toolError(
          `No Swymble lab with id "${id}". Available ids: ${data.labs.map((entry) => entry.id).join(', ')}.`,
        );
      }

      return toolResult(lab);
    }

    case 'list_swymble_projects':
      return toolResult({ count: data.projects.length, projects: data.projects });

    case 'search_swymble_writing': {
      const query = readStringArg(args, 'query').toLowerCase();
      const posts = data.posts.filter(
        (post) => !query || `${post.title} ${post.summary}`.toLowerCase().includes(query),
      );
      return toolResult({ count: posts.length, query: query || null, posts });
    }

    default:
      return toolError(`Unknown tool "${name}".`);
  }
};

// ---------------------------------------------------------------------------
// MCP methods
// ---------------------------------------------------------------------------

const handleRpc = async (message) => {
  const { id, method, params } = message;

  switch (method) {
    case 'initialize': {
      const requested = params?.protocolVersion;
      const protocolVersion =
        typeof requested === 'string' && SUPPORTED_PROTOCOL_VERSIONS.includes(requested)
          ? requested
          : DEFAULT_PROTOCOL_VERSION;

      return rpcResult(id, {
        protocolVersion,
        capabilities: { tools: { listChanged: false } },
        serverInfo: { name: SERVER_NAME, version: SERVER_VERSION },
        instructions:
          'Read-only access to Swymble\'s public content: the studio overview, Swymble Labs products, client projects and blog posts. Start with get_swymble_overview, then get_swymble_lab for a specific product.',
      });
    }

    case 'ping':
      return rpcResult(id, {});

    case 'tools/list':
      return rpcResult(id, { tools: TOOL_DEFINITIONS });

    case 'tools/call': {
      const name = typeof params?.name === 'string' ? params.name : '';

      if (!TOOL_NAMES.has(name)) {
        // Length-capped before being echoed, so a caller cannot use the error string as an
        // amplifier or push arbitrary text into whatever logs this.
        return rpcError(id, JSON_RPC_INVALID_PARAMS, `Unknown tool: ${name.slice(0, 64)}`);
      }

      const args = params?.arguments;

      if (args !== undefined && (typeof args !== 'object' || args === null || Array.isArray(args))) {
        return rpcError(id, JSON_RPC_INVALID_PARAMS, 'Tool arguments must be an object.');
      }

      try {
        return rpcResult(id, await runTool(name, args ?? {}));
      } catch (error) {
        // The upstream failure is ours, not the caller's — report it as a tool error so the
        // client can retry, without leaking internals beyond the message.
        return rpcResult(id, toolError(`Swymble site data is temporarily unavailable: ${error.message}`));
      }
    }

    default:
      return rpcError(id, JSON_RPC_METHOD_NOT_FOUND, `Method not found: ${String(method).slice(0, 64)}`);
  }
};

const isNotification = (message) => message?.id === undefined;

export default {
  async fetch(request) {
    const url = new URL(request.url);

    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: corsHeaders() });
    }

    // A GET on /mcp is how clients open a server-initiated SSE stream. This server is stateless
    // and never initiates anything, so saying so plainly beats leaving a stream open forever.
    if (request.method === 'GET') {
      if (url.pathname === '/mcp') {
        return jsonResponse({ error: 'This MCP server is stateless; use POST /mcp.' }, 405);
      }

      return jsonResponse(
        {
          name: SERVER_NAME,
          version: SERVER_VERSION,
          transport: { type: 'streamable-http', endpoint: `${url.origin}/mcp` },
          documentation: 'https://swymble.com/llms.txt',
        },
        200,
      );
    }

    if (request.method !== 'POST' || url.pathname !== '/mcp') {
      return jsonResponse({ error: 'Not found. The MCP endpoint is POST /mcp.' }, 404);
    }

    // Reject oversized bodies before reading them. Content-Length can be absent or wrong, so the
    // decoded length is checked again after reading.
    const declaredLength = Number(request.headers.get('Content-Length') ?? '0');

    if (Number.isFinite(declaredLength) && declaredLength > MAX_BODY_BYTES) {
      return jsonResponse(rpcError(null, JSON_RPC_INVALID_REQUEST, 'Request body too large.'), 413);
    }

    const rawBody = await request.text();

    if (rawBody.length > MAX_BODY_BYTES) {
      return jsonResponse(rpcError(null, JSON_RPC_INVALID_REQUEST, 'Request body too large.'), 413);
    }

    let body;

    try {
      body = JSON.parse(rawBody);
    } catch {
      return jsonResponse(rpcError(null, JSON_RPC_PARSE_ERROR, 'Invalid JSON.'), 400);
    }

    // A batch is an array; a single call is an object. Batches are capped so one request cannot
    // fan out into an unbounded amount of work.
    const messages = Array.isArray(body) ? body : [body];

    if (messages.length === 0 || messages.length > 20) {
      return jsonResponse(rpcError(null, JSON_RPC_INVALID_REQUEST, 'Batch must contain 1-20 messages.'), 400);
    }

    const responses = [];

    for (const message of messages) {
      if (typeof message !== 'object' || message === null || Array.isArray(message)) {
        responses.push(rpcError(null, JSON_RPC_INVALID_REQUEST, 'Each message must be an object.'));
        continue;
      }

      if (typeof message.method !== 'string') {
        responses.push(rpcError(message.id, JSON_RPC_INVALID_REQUEST, 'Missing "method".'));
        continue;
      }

      // Notifications (no id) get no reply, per JSON-RPC. `notifications/initialized` is the one
      // every client sends right after initialize.
      if (isNotification(message)) {
        continue;
      }

      try {
        responses.push(await handleRpc(message));
      } catch (error) {
        responses.push(rpcError(message.id, JSON_RPC_INTERNAL_ERROR, error.message));
      }
    }

    if (responses.length === 0) {
      return new Response(null, { status: 202, headers: corsHeaders() });
    }

    return jsonResponse(Array.isArray(body) ? responses : responses[0]);
  },
};
